routes/web.php
            Route::get('paypal-invoice-download/{id}', array('as' => 'paypal.invoice-download','uses' => 'AdminPaypalController@paypalInvoiceDownload',));

            // route for view/blade file
            Route::get('paywithpaypal', array('as' => 'paywithpaypal','uses' => 'AdminPaypalController@payWithPaypal',));
            // route for post request
            Route::get('paypal/{packageId}/{type}', array('as' => 'paypal','uses' => 'AdminPaypalController@paymentWithpaypal',));
            Route::get('paypal/cancel-subscription', array('as' => 'paypal.cancel-subscription','uses' => 'AdminPaypalController@cancelSubscription',));
            Route::get('paypal/cancel-agreement', array('as' => 'paypal.cancel-agreement','uses' => 'AdminPaypalController@cancelAgreement',));

            // route for check status responce
            Route::get('paypal', array('as' => 'status','uses' => 'AdminPaypalController@getPaymentStatus',));
            Route::get('subscribe/invoice', 'ManageSubscriptionController@invoice')->name('subscribe.invoice');
            Route::get('subscribe/data', 'ManageSubscriptionController@data')->name('subscribe.data');
            Route::get('subscribe/history-data', 'ManageSubscriptionController@historyData')->name('subscribe.history-data');
            Route::get('subscribe/cancel-subscription/{type?}', 'ManageSubscriptionController@cancelSubscription')->name('subscribe.cancel-subscription');
            Route::post('subscribe/payment-stripe', 'ManageSubscriptionController@payment')->name('payments.stripe');
            Route::get('subscribe/select-package/{packageID}',  'ManageSubscriptionController@selectPackage')->name('subscribe.select-package');
            Route::get('subscribe/invoice-download/{invoice}', 'ManageSubscriptionController@download')->name('subscribe.invoice-download');
            Route::get('subscribe/default-invoice-download/{invoice}', 'ManageSubscriptionController@invoiceDownload')->name('subscribe.default-invoice-download');
            Route::get('subscribe/paypal-invoice-download/{id}', array('as' => 'subscribe.paypal-invoice-download','uses' => 'ManageSubscriptionController@paypalInvoiceDownload',));
            Route::get('subscribe/history', array('as' => 'subscribe.history','uses' => 'ManageSubscriptionController@history',));
            Route::get('subscribe/razorpay-invoice-download/{id}', 'ManageSubscriptionController@razorpayInvoiceDownload')->name('subscribe.razorpay-invoice-download');
            Route::post('subscribe/razorpay-payment',  'ManageSubscriptionController@razorpayPayment')->name('subscribe.razorpay-payment');
            Route::post('subscribe/razorpay-subscription',  'ManageSubscriptionController@razorpaySubscription')->name('subscribe.razorpay-subscription');
            Route::resource('subscribe', 'ManageSubscriptionController');

            Route::post('todo-items/update-todo-item', 'AdminTodoItemController@updateTodoItem')->name('todo-items.updateTodoItem');
            Route::resource('todo-items', 'AdminTodoItemController');
            Route::resource('report', 'AdminReportController');
        }
    );
    
    Route::get('applications-archive/data', 'AdminApplicationArchiveController@data')->name('applications-archive.data');
    Route::get('applications-archive/export/{skill}', 'AdminApplicationArchiveController@export')->name('applications-archive.export');
    
    

    Route::group(
        ['namespace' => 'SuperAdmin', 'prefix' => 'super-admin', 'as' => 'superadmin.', 'middleware' => ['super-admin']],
        function () {
       
            Route::get('applications-archive/data', 'SuperAdminApplicationArchiveController@data')->name('applications-archive.data');
            Route::get('applications-archive/export/{skill}', 'SuperAdminApplicationArchiveController@export')->name('applications-archive.export');
            Route::resource('applications-archive', 'SuperAdminApplicationArchiveController');
            // Route::get('applications-archive/data', 'AdminApplicationArchiveController@data')->name('applications-archive.data');
            // Route::get('applications-archive/export/{skill}', 'AdminApplicationArchiveController@export')->name('applications-archive.export');
            // Route::get('/applications-archive',  ['uses' => 'SuperAdminApplicationArchiveController@index','as'=>'applications-archive.index'])->name('applications-archive.index');
            Route::resource('profile', 'SuperAdminProfileController');
            Route::resource('dashboard', 'SuperAdminDashboardController');
            Route::get('smtp-settings/sent-test-email', ['uses' => 'SuperAdminSmtpSettingController@sendTestEmail'])->name('smtp-settings.sendTestEmail');
            Route::resource('smtp-settings', 'SuperAdminSmtpSettingController');
            Route::resource('subscribe', 'ManageSubscriptionController');
            //language settings
            Route::get('language-settings/change-language', ['uses' => 'LanguageSettingsController@changeLanguage'])->name('language-settings.change-language');
            Route::put('language-settings/change-language-status/{id}', 'LanguageSettingsController@changeStatus')->name('language-settings.changeStatus');
            Route::resource('language-settings', 'LanguageSettingsController');

            Route::resource('theme-settings', 'SuperAdminThemeSettingsController')
            ;

            Route::put('footer-settings/update-footer-menu/{id}', 'SuperAdminFooterSettingsController@updateFooterMenu')->name('footer-settings.updateFooterMenu');
            Route::post('footer-settings/store-footer-menu', 'SuperAdminFooterSettingsController@storeFooterMenu')->name('footer-settings.storeFooterMenu');
            Route::get('footer-settings/data', 'SuperAdminFooterSettingsController@data')->name('footer-settings.data');
            Route::resource('footer-settings', 'SuperAdminFooterSettingsController');

            Route::post('update-application/deleteFile', ['uses' => 'UpdateApplicationController@deleteFile'])->name('update-application.deleteFile');
            Route::get('update-application/update', ['as' => 'update-application.updateApp', 'uses' => 'UpdateApplicationController@update']);
            Route::get('update-application/download', ['as' => 'update-application.download', 'uses' => 'UpdateApplicationController@download']);
            Route::get('update-application/downloadPercent', ['as' => 'update-application.downloadPercent', 'uses' => 'UpdateApplicationController@downloadPercent']);
            Route::get('update-application/checkIfFileExtracted', ['as' => 'update-application.checkIfFileExtracted', 'uses' => 'UpdateApplicationController@checkIfFileExtracted']);
            Route::get('update-application/install', ['as' => 'update-application.install', 'uses' => 'UpdateApplicationController@install']);
            Route::resource('update-application', 'UpdateApplicationController');


            Route::post('company/updateCompanyPackage/{id}', 'SuperAdminCompanyController@updateCompanyPackage')->name('company.updateCompanyPackage');
            Route::get('company/changePackage/{id}', 'SuperAdminCompanyController@changePackage')->name('company.changePackage');
            Route::get('company/data', 'SuperAdminCompanyController@data')->name('company.data');
            Route::post('company/{id}/login', 'SuperAdminCompanyController@loginAsCompany')->name('company.loginAsCompany');
            Route::resource('company', 'SuperAdminCompanyController');

            Route::resource('global-settings', 'GlobalSettingController');
            Route::get('linkedin-settings/update-status/{id}', 'LinkedInSettingController@updateStatus')->name('updateStatus');
            Route::resource('linkedin-settings', 'LinkedInSettingController');

            Route::get('front-cms/index', ['as' => 'front-cms.index', 'uses' => 'SuperAdminFrontCmsController@index']);
            Route::get('front-cms/change-form', 'SuperAdminFrontCmsController@changeForm')->name('front-cms.changeForm');
            Route::post('front-cms/update-common-header', ['as' => 'front-cms.updateCommonHeader', 'uses' => 'SuperAdminFrontCmsController@updateCommonHeader']);
            Route::post('front-cms/update-header', ['as' => 'front-cms.updateHeader', 'uses' => 'SuperAdminFrontCmsController@updateHeader']);
            Route::get('front-cms/features', ['as' => 'front-cms.features', 'uses' => 'SuperAdminFrontCmsController@imageFeatures']);
            Route::post('front-cms/features', ['as' => 'front-cms.savefeatures', 'uses' => 'SuperAdminFrontCmsController@saveImageFeatures']);
            Route::post('front-cms/features/{id}', ['as' => 'front-cms.updatefeatures', 'uses' => 'SuperAdminFrontCmsController@updatefeatures']);
            Route::get('front-cms/features/{id}', ['as' => 'front-cms.editfeatures', 'uses' => 'SuperAdminFrontCmsController@editImageFeatures']);
            Route::post('front-cms/deleteFeature/{id}', ['as' => 'front-cms.deleteFeature', 'uses' => 'SuperAdminFrontCmsController@deleteFeature']);

            Route::resource('icon-features', 'FrontIconFeatureController');

            Route::resource('client-feedbacks', 'ClientFeedbackController');

            Route::resource('packages', 'PackageController');
            Route::resource('currency-settings', 'SuperAdminCurrencyController');
            Route::resource('/payment-settings', 'SuperAdminPaymentSettingsController', ['only' => ['index', 'update']]);
            Route::resource('/sms-settings', 'SuperAdminSmsSettingsController', ['only' => ['index', 'update']]);

            Route::get('invoices/invoice-download/{invoice}', 'InvoiceController@download')->name('invoices.invoice-download');
            Route::get('invoices/paypal-invoice-download/{id}', array('as' => 'invoices.paypal-invoice-download','uses' => 'InvoiceController@paypalInvoiceDownload',));

app/Http/Controllers/SuperAdmin/ClientFeedbackController.php
<?php

namespace App\Http\Controllers\SuperAdmin;

use Illuminate\Http\Request;
use App\ClientFeedback;
use App\Http\Requests\SuperAdmin\StoreClientFeedback;
use App\Helper\Reply;
use App\LanguageSetting;

class ClientFeedbackController extends SuperAdminBaseController
{
    public function __construct()
    {
        parent::__construct();
        $this->pageIcon = 'icon-screen-desktop';
        $this->pageTitle = 'menu.clientFeedbacks';
    }

    public function index() {
        $this->feedbacks = ClientFeedback::with('language:id,language_name')->get();
        $this->activeLanguages = LanguageSetting::where('status', 'enabled')->orderBy('language_name', 'asc')->get();

        return view('super-admin.feedback.index', $this->data);
    }

    public function store(StoreClientFeedback $request) {
        $feedback = new ClientFeedback();
        $feedback->client_title = $request->client_title;
        $feedback->feedback = $request->feedback;
        $feedback->language_settings_id = $request->language;
        $feedback->save();

         return Reply::redirect(route('superadmin.client-feedbacks.index'), __('menu.clientFeedbacks') . ' ' . __('messages.updatedSuccessfully'));
    }

    public function edit($id) {
        $this->feedback = ClientFeedback::with('language:id,language_name,status')->where('id', $id)->first();
        $this->activeLanguages = LanguageSetting::where('status', 'enabled')->orderBy('language_name', 'asc')->get();

        return view('super-admin.feedback.edit', $this->data);
    }


    public function update(StoreClientFeedback $request, $id) {
        $feedback = ClientFeedback::findOrFail($id);
        $feedback->client_title = $request->client_title;
        $feedback->feedback = $request->feedback;
        $feedback->language_settings_id = $request->language;
        $feedback->save();

         return Reply::redirect(route('superadmin.client-feedbacks.index'), __('menu.clientFeedbacks') . ' ' . __('messages.updatedSuccessfully'));
    }

    public function destroy($id) {
        ClientFeedback::destroy($id);
        return Reply::success(__('messages.recordDeleted'));
    }
}

app/Http/Controllers/SuperAdmin/CustomModuleController.php
<?php

namespace App\Http\Controllers\SuperAdmin;

use App\Helper\Reply;
use App\Traits\ModuleVerify;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Session;
use Nwidart\Modules\Facades\Module;
use Zip;

class CustomModuleController extends SuperAdminBaseController
{
    use ModuleVerify;

    public function __construct()
    {
        parent::__construct();
        $this->pageTitle = 'menu.customModules';
        $this->pageIcon = 'icon-settings';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->type = 'custom';
        $this->updateFilePath = config('froiden_envato.tmp_path');
        $this->allModules = Module::all();
        return view('super-admin.custom-modules.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->type = 'custom';
        $this->updateFilePath = config('froiden_envato.tmp_path');
        return view('super-admin.custom-modules.install', $this->data);
    }

    /**
     * @param Request $request
     * @return array
     * @throws \Exception
     */
    public function store(Request $request)
    {
        File::put(public_path() . '/install-version.txt', 'complete');

        $filePath = $request->filePath;
        $zip = Zip::open($filePath);
        $array = explode('/', $filePath);
        $zipName  = end($array);
        $moduleName = str_replace('.zip', '', $zipName);

        // Extract the files to storage folder first for checking the right plugin
        $zip->extract(storage_path('app') . '/Modules');

        if ($this->validateModule($moduleName)) {
            // Move files to Modules if modules belongs to this product
            File::moveDirectory(storage_path('app') . '/Modules/' . $moduleName, base_path() . '/Modules/' . $moduleName, true);

            $this->flushData();
            return Reply::success('Installed successfully.');
        }
        return Reply::error('The zip that you are trying to install doesn\'t belongs to this product');
    }

    public function validateModule($moduleName)
    {
        if (file_exists(storage_path('app') . '/Modules/' . $moduleName . '/Config/config.php')) {
            $config = require_once storage_path('app') . '/Modules/' . $moduleName . '/Config/config.php';
            if (isset($config['parent_envato_id']) && ($config['parent_envato_id'] == config('froiden_envato.envato_item_id'))) {
                return true;
            }
        }

        return false;
    }

    private function flushData()
    {
        Artisan::call('optimize:clear');
        Artisan::call('module:migrate');

        session()->forget('check_migrate_status');

        Session::flush();
        Auth::logout();
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return $this->verifyModulePurchase($id);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $module = Module::find($id);

        if ($request->status == 'active') {
            $module->enable();
        } else {
            $module->disable();
        }

        $plugins = \Nwidart\Modules\Facades\Module::allEnabled();

        foreach ($plugins as $plugin) {
            Artisan::call('module:migrate', array($plugin, '--force' => true));
        }

        session()->forget('check_migrate_status');
        session(['worksuite_plugins' => array_keys($plugins)]);
    }

    public function verifyingModulePurchase(Request $request)
    {
        $request->validate([
            'purchase_code' => 'required|max:80',
        ]);

        $module = $request->module;
        $purchaseCode = $request->purchase_code;
        return $this->modulePurchaseVerified($module, $purchaseCode);
    }
}

app/Http/Controllers/SuperAdmin/SuperAdminSmsSettingsController.php
<?php

namespace App\Http\Controllers\SuperAdmin;

use App\Helper\Reply;
use App\Http\Requests\SuperAdmin\SmsSetting\UpdateRequest;
use App\Package;
use App\SmsSetting;
use App\Traits\PaymentSettings;


class SuperAdminSmsSettingsController extends SuperAdminBaseController
{
    use PaymentSettings;

    public function __construct() {
        parent::__construct();
        $this->pageTitle = 'app.sms.smsCredential';
        $this->pageIcon = 'icon-settings';
    }

    public function index() {
        $this->credentials = SmsSetting::first();
        return view('super-admin.sms-setting.index', $this->data);
    }

    public function update(UpdateRequest $request) {
        $smsSetting = SmsSetting::first();

        // Save SMS Credentials
        $smsSetting->nexmo_status = $request->nexmo_status;
        $smsSetting->nexmo_key = $request->nexmo_key;
        $smsSetting->nexmo_secret = $request->nexmo_secret;
        $smsSetting->nexmo_from = $request->nexmo_from;

        $smsSetting->save();
        
        return Reply::success(__('messages.updatedSuccessfully'));
    }
}

resources/views/super-admin/footer-settings/copyright-input.blade.php
<div class="form-group" data-language-id="{{ !empty($footerSettings) ? $footerSettings->language_settings_id : $languageId }}">
    <h5 class="box-title">@lang('modules.footerSettings.copyrightText')</h5>
    <input type="text" name="footer_copyright_text" class="form-control" value="{{ !empty($footerSettings) ? $footerSettings->footer_copyright_text : '' }}" />
</div>

resources/views/super-admin/footer-settings/index.blade.php
@extends('layouts.app')

@push('head-script')
    <link rel="stylesheet" href="//cdn.datatables.net/fixedheader/3.1.5/css/fixedHeader.bootstrap.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap.min.css">
@endpush

@section('content')

    <div class="row">
        <div class="col-12">
            <!-- Card -->
            <div class="card">
                <div class="card-body">
                    <form action="" class="ajax-form" id="createForm" method="POST">
                        @csrf
                        <h4 class="box-title">@lang('modules.footerSettings.footerSettings')</h4>
                        <hr>
                        {{-- <div class="form-group">
                            <select name="language" class="form-control selectpicker" id="language_switcher" onchange="changeForm();">
                                @forelse ($activeLanguages as $language)
                                <option
                                        value="{{ $language->id }}" data-content=' <span class="flag-icon  @if($language->language_code == 'en') flag-icon-us @else  flag-icon-{{ $language->language_code }} @endif"></span> {{ ucfirst($language->language_code) }}'>{{ ucfirst($language->language_code) }}</option>
                                @empty
                                @endforelse
                            </select>
                        </div> --}}
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            @forelse ($activeLanguages as $language)
                                <li class="nav-item">
                                    <a 
                                        class="nav-link @if($language->language_code == 'en') active @endif"
                                        id="{{$language->language_code}}-tab"
                                        data-toggle="tab"
                                        data-language-id="{{$language->id}}"
                                        href="#{{$language->language_code}}"
                                        role="tab"
                                        aria-controls="{{$language->language_code}}"
                                        aria-selected="true"
                                    >
                                        <span class="flag-icon  @if($language->language_code == 'en') flag-icon-us @else  flag-icon-{{ $language->language_code }} @endif"></span> {{ ucfirst($language->language_name) }}
                                    </a>
                                </li>
                            @empty
                            @endforelse
                        </ul>
                        <div id="copyright-section">
                            @include('super-admin.footer-settings.copyright-input', $footerSettings)
                        </div>
                        <div class="form-group">
                            <h5 class="box-title">@lang('modules.footerSettings.socialLinks')</h5>
                            <span class="text-danger">@lang('modules.footerSettings.socialLinksNote')</span><br><br>
                            <div class="row">
                                @forelse($footerSettings->social_links as $link)
                                    <div class="col-sm-12 col-md-3">
                                        <div class="form-group">
                                            <label for="{{ $link['name'] }}">
                                                @lang('modules.footerSettings.'.$link['name'])
                                            </label>
                                            <input
                                                class="form-control"
                                                id="{{ $link['name'] }}"
                                                name="social_links[{{ $link['name'] }}]"
                                                type="url"
                                                value="{{ $link['link'] }}"
                                                placeholder="@lang('modules.footerSettings.enter'.ucfirst($link['name']).'Link')">
                                        </div>
                                    </div>
                                @empty
                                
                                @endforelse
                            </div>
                        </div>
                        <button class="btn btn-success" id="save-form" type="button"><i class="fa fa-check"></i> @lang('app.save')</button>
                    </form>
                    <hr>
                    <div id="footer-menu-setting">
                        <h4 class="box-title">@lang('modules.footerSettings.footerMenuSetting')</h4>
                        <button class="btn btn-sm btn-primary" onclick="javascript:createNewFooterMenuSetting();">@lang('app.createNew')</button>
                        <div class="table-responsive mt-3">
                            <table id="myTable" class="table table-bordered table-striped ">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>@lang('app.name')</th>
                                        <th>@lang('app.description')</th>
                                        <th>@lang('app.language')</th>
                                        <th>@lang('app.action')</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('footer-script')
    <script src="//cdn.datatables.net/fixedheader/3.1.5/js/dataTables.fixedHeader.min.js"></script>
    <script src="//cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="//cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap.min.js"></script>
    <script>
        function createNewFooterMenuSetting() {
            let url = "{{ route('superadmin.footer-settings.create') }}"

            $.ajaxModal('#application-lg-modal', url);
        }

        function updateNewFooterMenuSetting(id) {
            let url = "{{ route('superadmin.footer-settings.edit', ':id') }}";
            url = url.replace(':id', id);

            $.ajaxModal('#application-lg-modal', url);
        }

        $('a[data-toggle="tab"]').on('show.bs.tab', function (e) {
            changeForm(e.target);
        })

        function changeForm(target) {
            $.easyAjax({
                url: "{{ route('superadmin.footer-settings.index') }}",
                container: '#copyright-section',
                data: {
                    language_settings_id: $(target).data('language-id')
                },
                type: 'GET',
                success: function (response) {
                    if (response.status === 'success') {
                        $('#copyright-section').html(response.view);
                    }
                }
            })
        }

        var table = $('#myTable').dataTable({
            responsive: true,
            // processing: true,
            serverSide: true,
            ajax: '{!! route('superadmin.footer-settings.data') !!}',
            language: languageOptions(),
            "fnDrawCallback": function( oSettings ) {
                $("body").tooltip({
                    selector: '[data-toggle="tooltip"]'
                });
            },
            columns: [
                { data: 'DT_Row_Index'},
                { data: 'name', name: 'name' },
                { data: 'description', name: 'description' },
                { data: 'language', name: 'language' },
                { data: 'action', name: 'action', width: '20%' }
            ]
        });

        new $.fn.dataTable.FixedHeader( table );

        $('#save-form').click(function () {
            $.easyAjax({
                url: '{{route('superadmin.footer-settings.store')}}',
                type: "POST",
                container: '#createForm',
                data: $('#createForm').serialize()+'&language='+$('#myTab a.active').data('language-id'),
            })
        });

        $('body').on('click', '.sa-params', function(){
            var id = $(this).data('row-id');
            swal({
                title: "@lang('errors.areYouSure')",
                text: "@lang('errors.deleteWarning')",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "@lang('app.delete')",
                cancelButtonText: "@lang('app.cancel')",
                closeOnConfirm: true,
                closeOnCancel: true
            }, function(isConfirm){
                if (isConfirm) {

                    var url = "{{ route('superadmin.footer-settings.destroy',':id') }}";
                    url = url.replace(':id', id);

                    var token = "{{ csrf_token() }}";

                    $.easyAjax({
                        type: 'POST',
                        url: url,
                        data: {'_token': token, '_method': 'DELETE'},
                        success: function (response) {
                            if (response.status == "success") {
                                $.unblockUI();
                                // swal("Deleted!", response.message, "success");
                                table._fnDraw();
                            }
                        }
                    });
                }
            });
        });
    </script>
@endpush